# Generated by Django 3.1.1 on 2020-10-18 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='usuario_aadministrador',
            new_name='usuario_administrador',
        ),
    ]
