# Generated by Django 3.1.1 on 2020-11-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_auto_20201020_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=30, verbose_name='rol de usuario')),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='imagen',
        ),
    ]
