# Generated by Django 3.1.1 on 2020-11-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('Secretaría', 'Secretaría'), ('Profesional médico', 'Profesional médico'), ('Ventas', 'Ventas'), ('Técnico', 'Técnico'), ('Gerencia', 'Gerencia')], default='Secretaría', max_length=30),
        ),
    ]
