# Generated by Django 3.1.1 on 2020-11-19 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lente',
            name='lado',
            field=models.CharField(choices=[('Izquierda', 'Izquierda'), ('Derecha', 'Derecha')], max_length=20, null=True),
        ),
    ]
